---
title: "R Notebook"
author: hanlin.tang
date: 10/23/20
output: html_document
runtime: shiny
---

```{r}
library(shiny)
```

```{r}
ui <- fluidPage(
  titlePanel("Body Fat Calculator"),

  fluidRow(
    column(3, 
      wellPanel(
        h3("With Density"),
        h5("If you have data of your density determined from underwater weighing, this will provide a much accurate result."),
        numericInput("density", label = h3("Density"), value = 1),
        actionButton("calculate1", label = "calculate")
      ),
      wellPanel(
        h4("Without Density"),
        numericInput("abdomen", label = h3("Abdomen (cm)"), value = 1),
        numericInput("weight", label = h3("Weight (lbs)"), value = 1),
        numericInput("wrist", label = h3("Wrist (cm)"), value = 1),
        actionButton("calculate2", label= "calculate")
      )
    ),
    column(9,
      wellPanel(
        textOutput("result_text")
      )
    )
  )
)
```

```{r}


server <- function(input, output) {
  
  solve_by_density = function() {
    paste("Your body fat rate is:", 495/input$density - 450)
  }
  
  observeEvent(input$calculate1, {
      text_reactive$text <- solve_by_density()
  })
  
  observeEvent(input$calculate2, {
    text_reactive$text <- 'Model'
  })
  
  text_reactive <- reactiveValues(
    text = "No data has been submitted yet."
  )

  output$result_text <- renderText({
    text_reactive$text
  })
#  observeEvent(input$calculate1, solve_by_density())
    
  # ans = density_function()
}
```

```{r}
shinyApp(ui = ui, server = server)
```